const test=require('node:test'),assert=require('node:assert/strict');const {AI}=require('../desktop/core/ai.cjs'),{ChatGPTAuth}=require('../desktop/core/auth.cjs');
const scopes=['chatgpt.tokens.use.direct'];
function fixture(fetcher){let credentials={subject:'account-one',email:'fixture@example.com',client_id:'client',access_token:'old-access',refresh_token:'refresh-one',scopes,expires_at:Date.now()+3600000};const vault={get:key=>key==='chatgpt'?credentials:undefined,set:(key,value)=>{assert.equal(key,'chatgpt');credentials=value;}};return {vault,auth:new ChatGPTAuth(vault,async()=>{},fetcher)};}
const completed=text=>new Response('data: '+JSON.stringify({type:'response.output_text.delta',delta:text})+'\n\ndata: '+JSON.stringify({type:'response.completed',response:{usage:{input_tokens:1,output_tokens:1}}})+'\n\n');
const settings=()=>({provider:'chatgpt',model:'fixture-model'});
test('sixteen concurrent 401 responses share one refresh and retry only their own rejected requests',async()=>{
 let refreshes=0,old=0,fresh=0,release;const allOld=new Promise(r=>release=r);const f=fixture(async(_,options)=>{refreshes++;assert.equal(new URLSearchParams(options.body).get('refresh_token'),'refresh-one');await new Promise(r=>setImmediate(r));return Response.json({access_token:'new-access',refresh_token:'refresh-two',expires_in:3600,scope:scopes.join(' ')});});
 const fetcher=async(_,options)=>{const token=options.headers.Authorization;if(token==='Bearer old-access'){old++;if(old===16)release();await allOld;return Response.json({error:{code:'invalid_token'}},{status:401});}assert.equal(token,'Bearer new-access');fresh++;return completed(JSON.parse(options.body).input[0].content);};
 const out=await Promise.all(Array.from({length:16},(_,i)=>new AI(settings,f.auth,fetcher).generate('Write','Story '+i)));assert.equal(refreshes,1);assert.equal(old,16);assert.equal(fresh,16);assert.deepEqual(out.map(x=>x.text),Array.from({length:16},(_,i)=>'Story '+i));assert.equal(f.vault.get('chatgpt').refresh_token,'refresh-two');assert.equal(f.vault.get('chatgpt').subject,'account-one');
});
test('a 401 for an older token reuses the token already refreshed by another worker',async()=>{
 let calls=0;const f=fixture(async()=>assert.fail('Must not refresh rotated credentials twice'));const ai=new AI(settings,f.auth,async(_,options)=>{calls++;if(calls===1){assert.equal(options.headers.Authorization,'Bearer old-access');f.vault.set('chatgpt',{...f.vault.get('chatgpt'),access_token:'already-new',refresh_token:'rotated'});return new Response('',{status:401});}assert.equal(options.headers.Authorization,'Bearer already-new');return completed('Xong');});assert.equal((await ai.generate('Write','Story')).text,'Xong');assert.equal(calls,2);
});
test('normal requests wait for an ongoing forced refresh even if the old token has not reached its expiry',async()=>{
 let release,refreshes=0;const gate=new Promise(r=>release=r);const f=fixture(async()=>{refreshes++;await gate;return Response.json({access_token:'new-access',expires_in:3600,scope:scopes.join(' ')});});const forced=f.auth.access({force:true,rejectedToken:'old-access'});let settled=false;const normal=f.auth.access().then(v=>{settled=true;return v;});await new Promise(r=>setImmediate(r));assert.equal(settled,false);release();assert.deepEqual(await Promise.all([forced,normal]),['new-access','new-access']);assert.equal(refreshes,1);
});
test('failed refresh, revoked plan permission and repeated 401 stop without loops or changes to API-key connections',async()=>{
 for(const mode of ['refresh-failed','permission-revoked','still-401']){let requests=0,refreshes=0;const f=fixture(async()=>{refreshes++;return mode==='refresh-failed'?new Response('',{status:401}):Response.json({access_token:'new-access',expires_in:3600,scope:mode==='permission-revoked'?'openid':scopes.join(' ')});});const ai=new AI(settings,f.auth,async()=>{requests++;return new Response('',{status:401});});await assert.rejects(ai.generate('Write','Story'),mode==='refresh-failed'?/hết hạn/:mode==='permission-revoked'?/không còn được cấp/:/HTTP 401/);assert.equal(refreshes,1);assert.equal(requests,mode==='still-401'?2:1);if(mode!=='still-401')assert.equal(f.vault.get('chatgpt').access_token,'old-access');}
 let requests=0;const api=new AI(()=>({provider:'openai',model:'fixture',openaiKey:'key'}),{access:async()=>assert.fail('API keys must not use OAuth refresh')},async()=>{requests++;return new Response('',{status:401});});await assert.rejects(api.generate('Write','Story'),/HTTP 401/);assert.equal(requests,1);
});
