const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {Store}=require('../desktop/core/store.cjs');const {moveStorage}=require('../desktop/core/storage.cjs');const {parseFeed,signals,generateIdeas}=require('../desktop/core/ideas.cjs');
const input={title:'Truyện tiếng Việt',genre:'Tiên hiệp',premise:'Một hành trình mới',style:'Tự nhiên',target:1000,words:2000};
test('storage migration verifies copies, preserves source and commits only after validation',()=>{
 const temp=fs.mkdtempSync(path.join(os.tmpdir(),'viet-move-'));try{const store=new Store(path.join(temp,'old')),p=store.create(input);store.backup(p);let selected;const next=moveStorage(store.root,path.join(temp,'new'),root=>selected=root);assert.equal(next.root,selected);assert.equal(next.load(p.id).title,p.title);assert.equal(store.load(p.id).title,p.title);assert.equal(fs.readdirSync(path.join(next.root,'backups')).length,1);next.create({...input,title:'Truyện tiếp theo'});assert.equal(store.list().length,1);assert.equal(next.list().length,2);
 assert.throws(()=>moveStorage(store.root,next.root,()=>assert.fail()),/trống/);assert.throws(()=>moveStorage(store.root,path.join(store.root,'nested'),()=>assert.fail()),/không nằm/);
 }finally{fs.rmSync(temp,{recursive:true,force:true});}
});
test('failed copy never switches active directory or changes original story',()=>{const temp=fs.mkdtempSync(path.join(os.tmpdir(),'viet-fail-'));try{const store=new Store(path.join(temp,'old')),p=store.create(input);fs.writeFileSync(store.file(p.id),'broken json');let committed=false;assert.throws(()=>moveStorage(store.root,path.join(temp,'new'),()=>committed=true),/Chưa đổi/);assert.equal(committed,false);assert.equal(fs.readFileSync(store.file(p.id),'utf8'),'broken json');}finally{fs.rmSync(temp,{recursive:true,force:true});}});
const rss=(title='Tiểu thuyết &amp; phim',link='https://news.google.com/rss/articles/example',date=new Date().toUTCString())=>`<rss><channel><item><title>${title}</title><link>${link}</link><pubDate>${date}</pubDate><source url="https://example.com">Báo văn học</source></item></channel></rss>`;
test('web signals decode Vietnamese and exclude old, duplicate and unsafe source links',()=>{const now=Date.now();assert.equal(parseFeed(rss())[0].title,'Tiểu thuyết & phim');assert.equal(parseFeed(rss('X','file:///tmp/test')).length,0);assert.equal(parseFeed(rss('X','https://news.google.com/a',new Date(now-40*86400000).toUTCString())).length,0);assert.equal(parseFeed(rss()+rss()).length,1);});
test('fetch uses live query, reports errors and never invents signals when empty',async()=>{const data=await signals('truyện chuyển thể',async url=>{assert.equal(url.hostname,'news.google.com');assert.match(url.searchParams.get('q'),/when:30d/);return new Response(rss());});assert.equal(data.items.length,1);assert.ok(data.fetchedAt);await assert.rejects(signals('truyện',async()=>new Response('<rss/>')),/Không tìm thấy/);await assert.rejects(signals('truyện',async()=>new Response('',{status:503})),/HTTP 503/);});
test('ideas use supplied web evidence and reject fabricated citations',async()=>{const snapshot={query:'truyện',items:parseFeed(rss()),fetchedAt:new Date().toISOString()};const idea={title:'Hành trình',genre:'Tiên hiệp',premise:'Một người đi tìm bí mật',hook:'Bản đồ biến mất',direction:'Mỗi quyển một bí mật',basis:'Chủ đề chuyển thể',sourceIds:[1]};const ai={generate:async(instructions,input)=>{assert.match(instructions,/không bịa/i);assert.match(input,/Báo văn học/);return {text:JSON.stringify({ideas:[idea]}),usage:{input:10,output:20}};}};assert.equal((await generateIdeas(ai,snapshot,'Tiên hiệp')).ideas.length,1);idea.sourceIds=[2];await assert.rejects(generateIdeas(ai,snapshot,'Tiên hiệp'),/nguồn không hợp lệ/);});
