const test=require('node:test'),assert=require('node:assert/strict'),Module=require('node:module'),EventEmitter=require('node:events'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{pathToFileURL}=require('node:url'),sharp=require('sharp');
test('real IPC allows translation, cover, ideas, editing and exports while writing; controls and settings stay isolated',async()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'viet-independent-')),handlers={},events=[];let release;const gate=new Promise(r=>release=r),originalLoad=Module._load,originalFetch=global.fetch;
 class Window extends EventEmitter{constructor(){super();Window.win=this;this.webContents=new EventEmitter();this.webContents.send=(_,v)=>events.push(v);this.webContents.setWindowOpenHandler=()=>{};}loadFile(){}isDestroyed(){return false;}}
 const app=new EventEmitter();Object.assign(app,{setName(){},getPath:()=>root,setPath(){},getVersion:()=> '1.0.0',whenReady:()=>Promise.resolve(),quit(){},isPackaged:true});const updater=new EventEmitter();let checks=0;updater.checkForUpdates=async()=>{checks++;updater.emit('update-not-available');};
 const electron={app,BrowserWindow:Window,ipcMain:{handle:(name,fn)=>handlers[name]=fn},dialog:{showErrorBox:(_,msg)=>{throw new Error(msg);},showSaveDialog:async()=>({canceled:false,filePath:path.join(root,'export.zip')})},shell:{},safeStorage:{isEncryptionAvailable:()=>true,getSelectedStorageBackend:()=> 'libsecret',encryptString:s=>Buffer.from(s),decryptString:b=>b.toString()}};
 Module._load=function(name,...args){if(name==='electron')return electron;if(name==='electron-updater')return {autoUpdater:updater};return originalLoad.call(this,name,...args);};
 const image=(await sharp({create:{width:800,height:1200,channels:3,background:'#28585b'}}).png().toBuffer()).toString('base64');let storyCalls=0;
 global.fetch=async(url,options)=>{
  if(String(url).includes('news.google.com'))return new Response(`<rss><channel><item><title>Tin mẫu</title><link>https://news.google.com/rss/articles/test</link><pubDate>${new Date().toUTCString()}</pubDate><source>Nguồn mẫu</source></item></channel></rss>`);
  const body=JSON.parse(options.body);if(String(url).includes('/images/')){assert.equal(options.headers.Authorization,'Bearer image-key');return Response.json({data:[{b64_json:image}]});}
  const input=JSON.parse(body.input[0].content.split('\nLần trước')[0]);let value;
  if(input.title==='Đang viết'||input.context?.title==='Đang viết'){storyCalls++;assert.equal(body.model,'original-model');assert.equal(body.max_output_tokens,8192);assert.equal(options.headers.Authorization,'Bearer original-key');if(storyCalls===1)await gate;}
  if(input.task?.startsWith('Tạo hồ sơ'))value={bible:'Hồ sơ thế giới riêng',arcs:[{title:'Quyển',start:1,end:input.target,summary:'Hành trình'}]};
  else if(input.task?.startsWith('Lập chính xác')){const m=input.task.match(/chương (\d+) đến (\d+)/);value={chapters:Array.from({length:+m[2]-+m[1]+1},(_,i)=>({number:+m[1]+i,title:'Chương',plan:'Một cảnh'}))};}
  else if(input.task?.startsWith('Kiểm tra'))value={approved:true,issues:[],summary:'Một cảnh đã hoàn thành',facts:[],stateUpdates:{},openThreads:[]};
  else if(input.translation)value={approved:true,issues:[]};else if(input.source)value={text:'Lâm Phàm về nhà.',terms:[]};
  else if(input.sources)value={ideas:[{title:'Ý tưởng riêng',genre:'Phiêu lưu',premise:'Hành trình mới',hook:'Bí mật',direction:'Nhiều quyển',basis:'Suy luận từ tin mẫu',sourceIds:[1]}]};
  else value='Nội dung truyện đang viết';
  const text=typeof value==='string'?value:JSON.stringify(value);return new Response('data: '+JSON.stringify({type:'response.output_text.delta',delta:text})+'\n\ndata: '+JSON.stringify({type:'response.completed',response:{usage:{input_tokens:1,output_tokens:1}}})+'\n\n');
 };
 try{
  require('../desktop/main.cjs');while(!handlers.init)await new Promise(r=>setImmediate(r));const event={sender:Window.win.webContents,senderFrame:{url:pathToFileURL(path.resolve(__dirname,'../desktop/ui/index.html')).href}};const call=async(name,input)=>{const r=await handlers[name](event,input);if(!r.ok)throw new Error(r.error);return r.data;};
  await call('settings:save',{provider:'openai',model:'original-model',openaiKey:'original-key',maxOutputTokens:8192});assert.equal((await call('init')).settings.maxOutputTokens,8192);await assert.rejects(call('settings:save',{provider:'openai',model:'a',maxOutputTokens:-1}));await assert.rejects(call('settings:save',{provider:'openai',model:'a',maxOutputTokens:1.5}));const input={genre:'Phiêu lưu',premise:'Hành trình',style:'Tự nhiên',target:2,words:300};const running=await call('projects:create',{...input,title:'Đang viết'});await call('cover:settings',{id:running.id,config:{auto:false}});await call('jobs:start',{id:running.id,count:2});while(!storyCalls)await new Promise(r=>setImmediate(r));
  const profile=await call('accounts:save',{name:'Kết nối phụ',provider:'gemini',model:'gemini-fixture',geminiKey:'second-profile-secret',enabled:true,maxParallel:2,maxOutputTokens:0});assert.equal(profile.pool.accounts.length,2);assert.ok(!JSON.stringify(profile).includes('second-profile-secret'));await call('accounts:configure',{enabled:true,primarySlots:2});await assert.rejects(call('accounts:save',{provider:'openai',model:'x',name:'Sai',enabled:true,maxParallel:17}));
  const other=await call('projects:create',{...input,title:'Truyện khác'});await call('projects:save',{id:other.id,bible:'Hồ sơ chỉnh riêng',style:'Tự nhiên'});await assert.rejects(call('projects:save',{id:running.id,bible:'Không được ghi đè',style:'Khác'}),/Dự án này/);
  await call('synopsis:save',{id:other.id,text:'Tóm tắt riêng truyện khác'});assert.equal((await call('projects:get',running.id)).synopsis,'');const draft=await call('synopsis:generate',other.id);assert.ok(draft.text);assert.equal((await call('projects:get',other.id)).synopsis,'Tóm tắt riêng truyện khác');await assert.rejects(call('synopsis:save',{id:running.id,text:'Không ghi đè khi viết'}),/Dự án này/);
  await call('images:save',{provider:'openai',model:'image-model',openaiKey:'image-key'});const cover=await call('cover:generate',{id:other.id});assert.equal(cover.cover.width,1200);await call('export',{id:other.id,format:'zip'});assert.ok(fs.existsSync(path.join(root,'export.zip')));
  const translated=await call('translation:create',{title:'Bản dịch độc lập',language:'zh',style:'Tự nhiên',glossary:'',text:'第1章 回家\n林凡回家。'});await call('translation:start',{id:translated.id,count:1});while((await call('init')).activity.translation)await new Promise(r=>setImmediate(r));assert.equal((await call('translation:get',translated.id)).chapters[0].status,'approved');
  await call('ideas:fetch','phiêu lưu');assert.equal((await call('ideas:generate','Phiêu lưu')).ideas.length,1);await call('update:check');assert.equal(checks,1);await assert.rejects(call('data:change'),/tạm dừng/i);
  await call('settings:save',{provider:'openai',model:'next-model',openaiKey:'next-key'});await call('translation:pause');assert.equal((await call('jobs:list')).active,1);release();while((await call('jobs:list')).active)await new Promise(r=>setImmediate(r));assert.equal((await call('projects:get',running.id)).chapters.filter(c=>c.status==='approved').length,2);assert.equal((await call('projects:get',other.id)).bible,'Hồ sơ chỉnh riêng');assert.ok(events.some(e=>e.type==='activity'&&e.translation));assert.ok(events.some(e=>e.type==='activity'&&e.cover));assert.ok(events.some(e=>e.type==='activity'&&e.ideas));assert.equal((await call('ai:limits')).status,'unknown');assert.ok(events.some(e=>e.type==='ai:limits'));assert.ok(!JSON.stringify(events.filter(e=>e.type==='ai:limits')).includes('original-key'));await call('accounts:remove',profile.id);assert.equal((await call('accounts:list')).accounts.length,1);
 }finally{release();global.fetch=originalFetch;Module._load=originalLoad;fs.rmSync(root,{recursive:true,force:true});}
});
