const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {Store}=require('../desktop/core/store.cjs');const {Engine}=require('../desktop/core/engine.cjs');const {JobQueue}=require('../desktop/core/queue.cjs');const {AI}=require('../desktop/core/ai.cjs');
const tick=()=>new Promise(r=>setImmediate(r));
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'viet-queue-')),store=new Store(root);return {root,store,create:(title,target=5)=>{const p=store.create({title,genre:'Phiêu lưu',premise:'Hành trình riêng của '+title,style:'Tự nhiên',target,words:300});p.bible='Hồ sơ riêng của '+title;p.arcs=[{title:'Quyển',start:1,end:target,summary:'Đi đến nơi cuối'}];store.save(p);return p;},done:()=>fs.rmSync(root,{recursive:true,force:true})};}
function response(input){const v=JSON.parse(input.split('\nLần trước')[0]),n=v.context?.chapter?.number||v.context?.number; // writer context has plan under current
 if(v.task.startsWith('Lập chính xác')){const [,a,b]=v.task.match(/chương (\d+) đến (\d+)/);return {chapters:Array.from({length:+b-+a+1},(_,i)=>({number:+a+i,title:'Chương '+(+a+i),plan:'Cảnh '+(+a+i)}))};}
 if(v.task.startsWith('Kiểm tra'))return {approved:true,issues:[],summary:'Đã viết '+v.content,facts:[v.content],stateUpdates:{nhanVat:v.content},openThreads:[]};
 return 'Nội dung riêng '+v.context.title+' '+v.task;
}
const generated=input=>({text:typeof response(input)==='string'?response(input):JSON.stringify(response(input)),usage:{input:1,output:1}});
async function settle(queue){for(let i=0;i<20000&&queue.busy();i++)await tick();assert.equal(queue.busy(),false);}
test('500 chapter batch survives repeated malformed outlines/reviews and preserves every checkpoint',async()=>{const f=fixture();try{const p=f.create('Truyện dài',500),bad=new Set();let retries=0;const engine=new Engine(f.store,{generate:async(_,input)=>{const request=JSON.parse(input.split('\nLần trước')[0]),key=request.task+(request.content||'');if((key.startsWith('Lập chính xác')||key.startsWith('Kiểm tra'))&&!bad.has(key)){bad.add(key);retries++;return {text:'{"wrong":true}',usage:{input:1,output:1}};}return generated(input);}});await engine.run(p.id,500);const q=f.store.load(p.id);assert.equal(q.job.status,'completed');assert.equal(q.chapters.filter(c=>c.status==='approved').length,500);assert.equal(q.memories.length,500);assert.equal(q.job.remaining,0);assert.equal(new Set(q.chapters.map(c=>c.number)).size,500);assert.ok(retries>=550);assert.match(q.chapters[499].content,/500/);}finally{f.done();}});
test('three stories obey concurrency cap, reject duplicate jobs and keep content isolated',async()=>{const f=fixture();try{const ps=['An','Bình','Chi'].map(x=>f.create(x));let inFlight=0,peak=0;const ai={generate:async(_,input)=>{inFlight++;peak=Math.max(peak,inFlight);await tick();const value=generated(input);inFlight--;return value;}};const q=new JobQueue(f.store,emit=>new Engine(f.store,ai,emit));q.setLimit(2);for(const p of ps)q.enqueue(p.id,5);assert.throws(()=>q.enqueue(ps[0].id,5),/đã chạy/);await settle(q);assert.equal(peak,2);for(const p of ps){const saved=f.store.load(p.id);assert.equal(saved.chapters.length,5);assert.ok(saved.chapters.every(c=>c.content.includes(p.title)));assert.equal(saved.job.remaining,0);}assert.equal(q.snapshot().items.length,0);}finally{f.done();}});
test('pause/restart restores remaining batch without restarting approved chapters or launching automatically',async()=>{const f=fixture();try{const p=f.create('Tiếp tục',10);let queue;const ai={generate:async(_,input)=>{await tick();return generated(input);}};queue=new JobQueue(f.store,emit=>new Engine(f.store,ai,emit),event=>{if(event.type==='saved'&&event.chapter===3)queue.pause(p.id);});queue.enqueue(p.id,10);await settle(queue);assert.equal(f.store.load(p.id).chapters.filter(c=>c.status==='approved').length,3);const before=f.store.load(p.id).chapters.slice(0,3).map(c=>c.content);const restart=new JobQueue(f.store,emit=>new Engine(f.store,ai,emit));assert.equal(restart.busy(),false);assert.equal(restart.snapshot().items[0].count,7);restart.resume(p.id);await settle(restart);const saved=f.store.load(p.id);assert.equal(saved.chapters.filter(c=>c.status==='approved').length,10);assert.deepEqual(saved.chapters.slice(0,3).map(c=>c.content),before);}finally{f.done();}});
test('one story failing validation does not stop another and queued work is durable',async()=>{const f=fixture();try{const bad=f.create('Hỏng'),good=f.create('Tốt');const q=new JobQueue(f.store,emit=>new Engine(f.store,{generate:async(_,input)=>{await tick();return input.includes('Hỏng')?{text:'bad JSON',usage:{}}:generated(input);}},emit));q.enqueue(bad.id,5);q.enqueue(good.id,5);await settle(q);assert.equal(f.store.load(good.id).chapters.filter(c=>c.status==='approved').length,5);assert.equal(q.snapshot().items[0].id,bad.id);assert.equal(q.snapshot().items[0].status,'paused');assert.equal(new JobQueue(f.store,()=>{}).snapshot().items[0].count,5);}finally{f.done();}});
const stream=text=>new Response(`data: ${JSON.stringify({type:'response.output_text.delta',delta:text})}\n\ndata: ${JSON.stringify({type:'response.completed'})}\n\n`);
test('temporary rate limit follows Retry-After and retries network failure; quota stops without replay',async()=>{let calls=0,waits=[],retries=[];const ai=new AI(()=>({provider:'openai',model:'test',openaiKey:'fake'}),{},async()=>{calls++;if(calls===1)throw new TypeError('fetch failed');if(calls===2)return Response.json({error:{code:'rate_limit_exceeded'}},{status:429,headers:{'retry-after':'1'}});return stream('Xong');},{sleep:async ms=>waits.push(ms),random:()=>0});const result=await ai.generate('Viết','Nội dung',{onRetry:e=>retries.push(e)});assert.equal(result.text,'Xong');assert.equal(calls,3);assert.equal(retries.length,2);assert.ok(waits[0]>=4900);assert.ok(retries[1].wait>=1000);
 let quotaCalls=0;const quota=new AI(()=>({provider:'openai',model:'test',openaiKey:'fake'}),{},async()=>{quotaCalls++;return Response.json({error:{code:'insufficient_quota'}},{status:429});});await assert.rejects(quota.generate('Viết','Truyện'),/Hết hạn mức/);assert.equal(quotaCalls,1);
});
test('partial streamed output and long Retry-After are never automatically replayed',async()=>{for(const fetcher of [async()=>new Response('data: {"type":"response.output_text.delta","delta":"Đã nhận một phần"}\n\n'),async()=>Response.json({error:{code:'slow_down'}},{status:429,headers:{'retry-after':'600'}})]){let calls=0;const ai=new AI(()=>({provider:'openai',model:'test',openaiKey:'fake'}),{},async(...args)=>{calls++;return fetcher(...args);});await assert.rejects(ai.generate('Viết','Truyện'));assert.equal(calls,1);}});
test('immediate pause cannot race a worker into making an AI call',async()=>{const f=fixture();try{const p=f.create('Chưa bắt đầu');let calls=0;const queue=new JobQueue(f.store,emit=>new Engine(f.store,{generate:async()=>{calls++;throw new Error('unexpected');}},emit));queue.enqueue(p.id,5);queue.pause(p.id,true);await settle(queue);assert.equal(calls,0);assert.equal(queue.snapshot().items[0].status,'paused');assert.equal(queue.snapshot().items[0].count,5);}finally{f.done();}});
test('hard quota pauses pending queue rather than repeating requests on each story',async()=>{const f=fixture();try{const projects=['Một','Hai','Ba'].map(x=>f.create(x));let requests=0;const queue=new JobQueue(f.store,emit=>new Engine(f.store,{generate:async()=>{requests++;const e=new Error('Hết hạn mức');e.quota=true;throw e;}},emit));queue.setLimit(1);for(const p of projects)queue.enqueue(p.id,5);await settle(queue);assert.equal(requests,1);assert.equal(queue.snapshot().items.filter(x=>x.status==='paused').length,3);}finally{f.done();}});
test('interrupted stream is saved separately and never treated as completed chapter',async()=>{const f=fixture();try{const p=f.create('Bị ngắt',1);p.chapters=[{number:1,title:'Chương 1',plan:'Một cảnh',content:'',status:'planned',wordCount:0,issues:[]}];f.store.save(p);const engine=new Engine(f.store,{generate:async()=>{const e=new Error('Kết nối bị ngắt');e.partialText='Một phần chưa hoàn tất';throw e;}});await engine.run(p.id,1);const q=f.store.load(p.id);assert.equal(q.chapters[0].content,'');assert.equal(q.chapters[0].interruptedDraft,'Một phần chưa hoàn tất');assert.equal(q.memories.length,0);assert.equal(q.job.remaining,1);assert.equal(q.job.status,'error');}finally{f.done();}});
