const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {Store}=require('../desktop/core/store.cjs');const {splitChapters,chunks,createTranslation,Translator,terms}=require('../desktop/core/translation.cjs');
const opts={title:'Truyện dịch',language:'zh',style:'Tiếng Việt tự nhiên, giữ nguyên ý',glossary:'林凡 = Lâm Phàm'};
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'viet-translate-'));return {root,store:new Store(root),done:()=>fs.rmSync(root,{recursive:true,force:true})};}
test('chapter splitting supports Chinese, English and convert without losing body paragraphs',()=>{
 for(const headings of [['第一章 开始','第二章 回家'],['Chapter 1: Start','Chapter 2: Home'],['Chương 1: Khởi đầu','Chương 2: Về nhà']]){const parts=splitChapters(headings[0]+'\nNội dung 1\n\nĐối thoại\n'+headings[1]+'\nNội dung 2');assert.equal(parts.length,2);assert.equal(parts[0].source,'Nội dung 1\n\nĐối thoại');assert.equal(parts[1].title,headings[1]);}
 assert.equal(splitChapters('Nội dung không có tiêu đề','Tên file')[0].title,'Tên file');assert.throws(()=>splitChapters('   '),/rỗng/);
});
test('long chapters split without dropping characters or breaking Unicode surrogate pairs',()=>{const source=('中英😀 văn bản.\n').repeat(1500),parts=chunks(source);assert.equal(parts.join(''),source);assert.ok(parts.every(p=>Array.from(p).length<=6000));assert.ok(parts.every(p=>!/[\uD800-\uDBFF]$/.test(p)));});
test('invalid glossary does not create a partial translation project',()=>{const f=fixture();try{assert.throws(()=>createTranslation(f.store,{...opts,glossary:'Tên không dấu bằng'},[{text:'Nội dung',title:'Chương'}]),/dạng/);assert.equal(f.store.list().length,0);assert.equal(terms('master = sư phụ').master,'sư phụ');}finally{f.done();}});
test('quota during review resumes saved translation instead of translating twice',async()=>{const f=fixture();try{const p=createTranslation(f.store,opts,[{title:'Chương 1',text:'林凡回家。'}]);let drafts=0,quota=true;const ai={generate:async(system,input)=>{assert.match(input,/Lâm Phàm/);if(system.includes('Bạn là dịch giả')){drafts++;return {text:JSON.stringify({text:'Lâm Phàm về nhà.',terms:[{source:'林凡',target:'Lâm Phàm'}]}),usage:{input:10,output:10}};}if(quota)throw new Error('Hết hạn mức');return {text:JSON.stringify({approved:true,issues:[]}),usage:{input:10,output:10}};}};const t=new Translator(f.store,ai);await t.run(p.id,1);let saved=f.store.load(p.id);assert.equal(saved.chapters[0].content,'Lâm Phàm về nhà.');assert.equal(saved.chapters[0].source,'林凡回家。');assert.equal(saved.chapters[0].segments[0].reviewed,false);quota=false;await new Translator(new Store(f.root),ai).run(p.id,1);saved=f.store.load(p.id);assert.equal(drafts,1);assert.equal(saved.chapters[0].status,'approved');assert.equal(saved.translation.glossary['林凡'],'Lâm Phàm');assert.equal(saved.usage.calls,2);}finally{f.done();}});
test('conflicting names pause translation without altering original or established terminology',async()=>{const f=fixture();try{const p=createTranslation(f.store,opts,[{title:'Chương',text:'林凡回家。'}]);const ai={generate:async system=>({text:JSON.stringify(system.includes('Bạn là dịch giả')?{text:'Lâm Phan về nhà.',terms:[{source:'林凡',target:'Lâm Phan'}]}:{approved:true,issues:[]}),usage:{input:1,output:1}})};await new Translator(f.store,ai).run(p.id,1);const saved=f.store.load(p.id);assert.equal(saved.chapters[0].status,'needs_review');assert.equal(saved.translation.glossary['林凡'],'Lâm Phàm');assert.equal(saved.chapters[0].source,'林凡回家。');assert.match(saved.chapters[0].issues.join(),/không khớp/);}finally{f.done();}});
test('pause finishes current draft, preserves source and saves resume point',async()=>{const f=fixture();try{const p=createTranslation(f.store,opts,[{title:'Chương',text:'林凡回家。'}]);let t;t=new Translator(f.store,{generate:async()=>{t.pause();return {text:JSON.stringify({text:'Lâm Phàm về nhà.',terms:[]}),usage:{input:1,output:1}};}});await t.run(p.id,1);const saved=f.store.load(p.id);assert.equal(saved.chapters[0].segments[0].reviewed,false);assert.equal(saved.chapters[0].content,'Lâm Phàm về nhà.');assert.equal(t.busy(),false);}finally{f.done();}});
