'use strict';
let editingAccount=null;
function accountsPage(){
 $('#crumb').textContent='Tài khoản AI';
 $('#content').innerHTML=`<div class="page-heading"><div><h1>Chia truyện cho nhiều tài khoản AI.</h1><p>Mỗi truyện giữ tài khoản và model; khi hết quota có thể tự chuyển sang kết nối dự phòng. Các chương vẫn được viết và kiểm tra tuần tự.</p></div></div><div class="panel"><label class="check-label"><input id="pool-enabled" type="checkbox" ${state.pool.enabled?'checked':''}>Tự phân phối truyện mới cho nhiều tài khoản</label><label class="check-label"><input id="quota-fallback" type="checkbox" ${state.pool.quotaFallback!==false?'checked':''}>Hết quota tự chuyển sang tài khoản AI khác</label><p class="hint">Dùng các kết nối đã bật và chọn model, kể cả khi tắt phân phối truyện mới. Model dự phòng có thể khác và dùng hạn mức hoặc phí của kết nối đó. Khi tất cả hết quota, app giữ tiến độ và tạm dừng.</p><label>Luồng tối đa của kết nối chính<input id="primary-slots" type="number" min="1" max="16" value="${state.pool.primarySlots}"></label><button id="pool-save" class="primary">Lưu cách phân phối</button><p class="hint">Tổng luồng vẫn theo mức chọn trong Hàng đợi. App ưu tiên tài khoản ít bận theo sức chứa; bỏ qua tài khoản chưa kết nối, đã tắt hoặc đang hết quota. Nhiều key chung một dự án có thể dùng chung hạn mức.</p></div><div id="account-rows"></div><div id="account-editor" class="panel"></div>`;
 bind('#pool-enabled','change',()=>state.dirty=true);bind('#quota-fallback','change',()=>state.dirty=true);bind('#primary-slots','input',()=>state.dirty=true);
 bind('#pool-save','click',e=>action(e.target,async()=>{state.pool=await api('accounts:configure',{enabled:$('#pool-enabled').checked,quotaFallback:$('#quota-fallback').checked,primarySlots:Number($('#primary-slots').value)});state.dirty=false;accountRows();toast('Đã lưu cách phân phối. Các đợt đang chạy giữ nguyên tài khoản.');}));accountRows();accountEditor(editingAccount);
}
function accountRows(){
 if(!$('#account-rows'))return;
 $('#account-rows').innerHTML=(state.pool?.accounts||[]).map(p=>`<div class="panel"><div class="section-row"><h3>${esc(p.name)}</h3><span class="status-pill">${p.blocked?'Đang chờ quota':!p.enabled?'Đã tắt':p.ready?'Sẵn sàng':'Chưa kết nối hoặc chưa chọn model'}</span></div><p>${esc(p.provider)} · ${esc(p.model)||'Chưa chọn model'} · tối đa ${p.maxParallel} luồng · ${(state.queue?.items||[]).filter(x=>x.status==='running'&&x.accountId===p.id).length} đang chạy</p>${p.chatgpt?.connected?`<p>Đã đăng nhập: ${esc(p.chatgpt.email)}</p>`:''}<p class="hint">${p.limits?.observedAt?'Phản hồi gần nhất: '+esc(new Date(p.limits.observedAt).toLocaleString('vi-VN')):'Chưa có số liệu hạn mức'}${p.limits?.requests?.remaining!=null?' · còn '+number(p.limits.requests.remaining)+' lượt trong cửa sổ hạn mức':''}${p.limits?.tokens?.remaining!=null?' · còn '+number(p.limits.tokens.remaining)+' token trong cửa sổ hạn mức':''}</p><button data-account-edit="${esc(p.id)}" class="secondary">${p.id==='primary'?'Mở kết nối chính':'Sửa tài khoản'}</button></div>`).join('');
 for(const button of $$('[data-account-edit]'))button.onclick=()=>action(button,async()=>{if(!await leave())return;if(button.dataset.accountEdit==='primary'){await navigate('settings');return;}editingAccount=button.dataset.accountEdit;accountEditor(editingAccount);});
}
function accountEditor(id=null){
 const p=(state.pool?.accounts||[]).find(p=>p.id===id)||{provider:'chatgpt',name:'',model:'',maxParallel:2,maxOutputTokens:0,enabled:true};editingAccount=p.id||null;
 $('#account-editor').innerHTML=`<h3>${p.id?'Sửa tài khoản AI':'Thêm tài khoản AI'}</h3><label>Tên để nhận biết<input id="account-name" maxlength="80" value="${esc(p.name)}" placeholder="Ví dụ: ChatGPT thứ hai"></label><label>Nguồn AI<select id="account-provider"><option value="chatgpt">ChatGPT — đăng nhập chính thức</option><option value="openai">OpenAI API</option><option value="experiential">Experiential Labs API</option><option value="gemini">Gemini API</option></select></label><div id="account-credentials"></div><div class="two"><label>Model<input id="account-model" list="account-model-options" maxlength="200" value="${esc(p.model)}"><datalist id="account-model-options"></datalist></label><div class="actions"><button id="account-models" class="secondary">Lấy model của tài khoản</button></div></div><div class="two"><label>Luồng tối đa<input id="account-slots" type="number" min="1" max="16" value="${p.maxParallel}"></label><label>Token đầu ra tối đa (0 = tự động)<input id="account-tokens" type="number" min="0" max="131072" value="${p.maxOutputTokens||0}"></label></div><label class="check-label"><input id="account-enabled" type="checkbox" ${p.enabled?'checked':''}>Cho phép phân phối truyện vào tài khoản này</label><div class="actions"><button id="account-save" class="primary">Lưu tài khoản AI</button><button id="account-test" class="secondary">Thử tài khoản</button>${p.id?'<button id="account-delete" class="quiet">Xóa tài khoản AI</button>':''}<button id="account-new" class="secondary">Thêm tài khoản khác</button></div><p class="hint">Thông tin kết nối được mã hóa riêng trên máy. Lượt thử dùng hạn mức AI. Khi hết quota, bấm Thử tài khoản hoặc Tiếp tục đợt đã lưu để thử lại. Ảnh bìa vẫn dùng API tạo ảnh riêng.</p>`;
 $('#account-provider').value=p.provider;accountCredentials(p);
 for(const selector of ['#account-name','#account-model','#account-slots','#account-tokens','#account-enabled'])bind(selector,'input',()=>state.dirty=true);
 bind('#account-provider','change',()=>{state.dirty=true;$('#account-model').value='';accountCredentials(p);});
 bind('#account-save','click',e=>action(e.target,async()=>{await saveAccount();accountEditor(editingAccount);toast('Đã lưu tài khoản AI.');}));
 bind('#account-models','click',e=>action(e.target,async()=>{const id=await saveAccount();const models=await api('accounts:models',id);$('#account-model-options').innerHTML=models.map(m=>`<option value="${esc(m.id)}">${esc(m.name)}</option>`).join('');toast('Đã lấy danh sách. Chọn model rồi lưu tài khoản.');}));
 bind('#account-test','click',e=>action(e.target,async()=>{const id=await saveAccount();const r=await api('accounts:test',id);state.pool=await api('accounts:list');accountRows();toast(r.text);}));
 bind('#account-new','click',async()=>{if(await leave())accountEditor();});
 bind('#account-delete','click',e=>action(e.target,async()=>{if(!confirm('Xóa thông tin kết nối tài khoản này? Nội dung truyện vẫn được giữ.'))return;state.pool=await api('accounts:remove',editingAccount);state.dirty=false;accountRows();accountEditor();}));
}
function accountCredentials(p){
 const provider=$('#account-provider').value;
 $('#account-credentials').innerHTML=provider==='chatgpt'?`<p>${p.chatgpt?.connected?'Đã đăng nhập: '+esc(p.chatgpt.email):'Bấm đăng nhập để app tự lưu hồ sơ và mở trình duyệt. Có thể để trống tên; app sẽ tự đặt tên. Chọn đúng tài khoản trong trình duyệt.'}</p><div class="actions"><button id="account-login" class="secondary">Đăng nhập ChatGPT riêng</button><button id="account-cancel" class="quiet">Hủy đăng nhập</button>${p.chatgpt?.connected?'<button id="account-logout" class="quiet">Đăng xuất tài khoản này</button>':''}</div>`:`<label>API key riêng<input id="account-key" type="password" autocomplete="off" placeholder="${(hasProviderKey(p,provider))?'Đã có key — để trống để giữ nguyên':'Nhập API key'}"></label>`;
 bind('#account-key','input',()=>state.dirty=true);
 bind('#account-login','click',e=>action(e.target,async()=>{const id=await saveAccount();await api('accounts:login',id);state.pool=await api('accounts:list');accountRows();accountEditor(id);toast('Đã kết nối tài khoản ChatGPT riêng.');}));
 bind('#account-cancel','click',()=>editingAccount&&api('accounts:cancel',editingAccount));
 bind('#account-logout','click',e=>action(e.target,async()=>{await api('accounts:logout',editingAccount);state.pool=await api('accounts:list');accountRows();accountEditor(editingAccount);}));
}
async function saveAccount(){
 const provider=$('#account-provider').value;for(const selector of ['#account-slots','#account-tokens']){if(!$(selector).reportValidity())throw new Error(selector==='#account-slots'?'Luồng tối đa phải là số nguyên từ 1 đến 16.':'Token đầu ra phải là số nguyên từ 0 đến 131072.');}
 let name=$('#account-name').value.trim();if(!name){const base=provider==='chatgpt'?'ChatGPT':providerName(provider)+' API',names=new Set((state.pool?.accounts||[]).filter(p=>p.id!==editingAccount).map(p=>p.name));let ordinal=2;while(names.has(base+' '+ordinal))ordinal++;name=base+' '+ordinal;$('#account-name').value=name;}
 const input={name,provider,model:$('#account-model').value.trim(),enabled:$('#account-enabled').checked,maxParallel:Number($('#account-slots').value),maxOutputTokens:Number($('#account-tokens').value)};if(editingAccount)input.id=editingAccount;
 if($('#account-key')?.value.trim())input[apiKeyField(provider)]=$('#account-key').value.trim();const result=await api('accounts:save',input);editingAccount=result.id;state.pool=result.pool;state.dirty=false;if($('#account-key'))$('#account-key').value='';accountRows();return editingAccount;
}
