'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=n=>Number(n||0).toLocaleString('vi-VN');
const state={page:'library',projects:[],project:null,tab:'chapters',chapter:null,settings:{},version:'',update:{},busy:false,dirty:false};
const api=(name,args)=>window.viet.call(name,args);let toastTimer;
function toast(message){$('#toast').textContent=message;$('#toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.add('hidden'),7000);}
async function action(button,fn){if(button)button.disabled=true;try{await fn();}catch(e){toast(e.message);}finally{if(button)button.disabled=false;}}
async function leave(){if(!state.dirty)return true;const ok=confirm('Bạn có thay đổi chưa lưu. Rời trang và bỏ các thay đổi này?');if(ok)state.dirty=false;return ok;}
function bind(selector,event,fn){const el=$(selector);if(el)el.addEventListener(event,fn);}
function connection(){const s=state.settings;const connected=s.provider==='chatgpt'?s.chatgpt?.connected:s.provider==='gemini'?s.hasGeminiKey:s.hasOpenaiKey;$('#connection-dot').classList.toggle('connected',!!connected);$('#connection-label').textContent=connected?(s.provider==='chatgpt'?'ChatGPT đã kết nối':s.provider==='gemini'?'Gemini API':'OpenAI API'):'Chưa kết nối AI';}
const art=`<svg class="hero-art" viewBox="0 0 300 230" aria-hidden="true"><ellipse cx="156" cy="207" rx="104" ry="10" fill="#dce2d0"/><path d="M52 67L140 91V204L52 179Z" fill="#6b8060"/><path d="M140 91L242 53V177L140 204Z" fill="#b7c5a2"/><path d="M61 54Q104 52 140 83Q179 49 230 44L234 171Q184 162 141 191Q105 161 61 170Z" fill="#faf8e9"/><path d="M140 83V191" stroke="#b2bd9d"/><g stroke="#d2d5bb" stroke-width="3"><path d="M76 84Q107 85 126 103M76 101Q108 102 126 117M76 120Q109 121 126 135M76 139Q109 139 126 154M156 103Q182 83 215 82M156 120Q182 101 215 99M156 138Q182 120 215 117M156 154Q182 139 215 136"/></g><path d="M218 155L261 58Q267 48 272 59L234 161L224 177Z" fill="#456348"/><path d="M224 177L218 155L234 161Z" fill="#c4a36c"/><path d="M218 155L224 177L219 173Z" fill="#45503c"/><path d="M249 58L260 64" stroke="#b7c5a2" stroke-width="3"/><circle cx="49" cy="38" r="3" fill="#a4b78d"/><path d="M96 24V35M91 29H102M258 186V195M254 191H263" stroke="#b7b887" stroke-width="2"/></svg>`;
function library(){
 state.page='library';$('#crumb').textContent='Thư viện truyện';
 const total=state.projects.reduce((s,p)=>s+p.completed,0),words=state.projects.reduce((s,p)=>s+p.words,0);
 $('#content').innerHTML=`<section class="hero"><div><div class="eyebrow">TỪ Ý TƯỞNG ĐẾN MỘT THẾ GIỚI</div><h1>Mỗi câu chuyện lớn,<br>bắt đầu từ một trang giấy.</h1><p>Cùng AI xây dựng thế giới, nuôi dưỡng nhân vật và viết từng chương trong hành trình sáng tác của bạn.</p><button id="new-project" class="primary">＋ Tạo truyện mới</button></div>${art}</section><div class="stats"><div class="stat"><span class="stat-icon">▤</span><div><strong>${state.projects.length}</strong><small>TRUYỆN TRONG THƯ VIỆN</small></div></div><div class="stat"><span class="stat-icon">✎</span><div><strong>${number(total)}</strong><small>CHƯƠNG ĐÃ KIỂM TRA</small></div></div><div class="stat"><span class="stat-icon">≋</span><div><strong>${number(words)}</strong><small>TỪ ĐÃ VIẾT</small></div></div></div><div class="section-row"><div><h2>Những thế giới của bạn</h2><p>Bản thảo được lưu sau mỗi bước viết.</p></div><div class="actions"><input id="search" class="search" aria-label="Tìm truyện" placeholder="Tìm tên truyện…"><button id="import-project" class="secondary">Nhập sao lưu</button></div></div><div id="cards" class="cards"></div>`;
 bind('#new-project','click',()=>$('#new-dialog').showModal());bind('#search','input',e=>cards(e.target.value));bind('#import-project','click',e=>action(e.target,async()=>{const p=await api('import');if(p){state.projects=await api('projects:list');await openProject(p.id);toast('Đã nhập thành bản truyện mới.');}}));cards();
}
function cards(search=''){
 const list=state.projects.filter(p=>p.title.toLocaleLowerCase('vi').includes(search.toLocaleLowerCase('vi')));
 $('#cards').innerHTML=list.length?list.map(p=>`<button class="card" data-id="${esc(p.id)}"><span class="tag">${esc(p.genre)}</span><h3>${esc(p.title)}</h3><p>${number(p.words)} từ · ${esc(new Date(p.updated).toLocaleDateString('vi-VN'))}</p><div class="bar"><div class="bar-fill" data-percent="${p.completed/p.target*100}"></div></div><div class="progress"><span>${p.completed} / ${p.target} chương</span><span>${Math.round(p.completed/p.target*100)}%</span></div></button>`).join(''):`<div class="empty"><div class="empty-symbol">✎</div><h3>${search?'Chưa tìm thấy truyện':'Trang giấy đang chờ bạn.'}</h3><p>${search?'Thử một tên khác.':'Tạo truyện đầu tiên, chọn hướng phát triển và để câu chuyện bắt đầu.'}</p></div>`;
 $$('.bar-fill').forEach(el=>el.style.width=el.dataset.percent+'%');$$('.card').forEach(el=>el.onclick=()=>action(el,()=>openProject(el.dataset.id)));
}
async function openProject(id){if(!await leave())return;state.project=await api('projects:get',id);state.page='project';state.chapter=state.project.chapters.find(c=>c.number===state.chapter?.number)||state.project.chapters.find(c=>c.content)||state.project.chapters[0]||null;state.busy=state.project.job?.status==='running';render();}
function workspace(){
 const p=state.project;$('#crumb').textContent=p.title;
 $('#content').innerHTML=`<div class="page-heading"><div><button id="back" class="quiet">← Thư viện truyện</button><h1>${esc(p.title)}</h1><p>${esc(p.genre)} · ${p.target} chương dự kiến · ${number(p.chapters.reduce((s,c)=>s+c.wordCount,0))} từ</p></div><div class="actions"><button id="export-txt" class="secondary">Xuất TXT</button><button id="export-json" class="secondary">Sao lưu</button></div></div><div class="panel"><div class="section-row"><div><h3>Nhịp sáng tác của bạn</h3><p>${esc(p.job?.message||'Bắt đầu bằng hồ sơ truyện, sau đó viết và kiểm tra từng chương.')}</p></div><span class="status-pill">${p.chapters.filter(c=>c.status==='approved').length} / ${p.target} chương</span></div><div class="actions"><label>Số chương trong đợt<input id="batch" type="number" value="5" min="1" max="1000"></label><button id="start-job" class="primary" ${state.busy?'disabled':''}>${p.chapters.length?'Tiếp tục viết →':'Viết đợt đầu →'}</button><button id="plan-job" class="secondary" ${state.busy?'disabled':''}>Tạo hồ sơ & dàn ý quyển</button><span class="hint">Có thể tạm dừng, kiểm tra rồi tiếp tục.</span></div></div><div class="tabs"><button data-tab="chapters" class="${state.tab==='chapters'?'active':''}">Bản thảo</button><button data-tab="outline" class="${state.tab==='outline'?'active':''}">Dàn ý quyển</button><button data-tab="bible" class="${state.tab==='bible'?'active':''}">Hồ sơ truyện</button><button data-tab="memory" class="${state.tab==='memory'?'active':''}">Bộ nhớ & dữ kiện</button></div><div id="tab-content"></div>`;
 bind('#back','click',()=>navigate('library'));bind('#export-txt','click',e=>exportProject(e.target,'txt'));bind('#export-json','click',e=>exportProject(e.target,'json'));
 const start=planOnly=>action($('#start-job'),async()=>{if(state.dirty)throw new Error('Hãy lưu thay đổi trước khi viết.');const count=Number($('#batch').value);await api('jobs:start',{id:p.id,count,planOnly});state.busy=true;$('#job-strip').classList.remove('hidden');$('#start-job').disabled=true;$('#plan-job').disabled=true;});bind('#start-job','click',()=>start(false));bind('#plan-job','click',()=>start(true));$$('[data-tab]').forEach(el=>el.onclick=async()=>{if(await leave()){state.tab=el.dataset.tab;workspace();}});tabContent();
}
async function exportProject(button,format){await action(button,async()=>{if(state.dirty)throw new Error('Lưu thay đổi trước khi xuất.');const result=await api('export',{id:state.project.id,format});if(result)toast('Đã lưu file: '+result);});}
const statusNames={planned:'Có dàn ý',draft:'Bản nháp',approved:'AI đã kiểm tra',needs_review:'Cần xem lại'};
function tabContent(){
 const p=state.project,el=$('#tab-content');
 if(state.tab==='outline'){el.innerHTML=p.arcs.length?`<div class="panel">${p.arcs.map((a,i)=>`<div class="arc"><small class="eyebrow">QUYỂN ${i+1} · CHƯƠNG ${a.start}–${a.end}</small><h3>${esc(a.title)}</h3><p>${esc(a.summary)}</p></div>`).join('')}</div>`:`<div class="empty"><h3>Vẽ đường đi cho câu chuyện.</h3><p>Bấm Tạo hồ sơ & dàn ý quyển phía trên.</p></div>`;return;}
 if(state.tab==='bible'){el.innerHTML=`<div class="panel"><h3>Thế giới, nhân vật và quy tắc</h3><p>Hồ sơ này được gửi cho AI mỗi lần viết và kiểm tra chương.</p><label>Hồ sơ truyện<textarea id="bible" rows="17">${esc(p.bible)}</textarea></label><label>Văn phong<textarea id="style" rows="3">${esc(p.style)}</textarea></label><button id="save-bible" class="primary" ${state.busy?'disabled':''}>Lưu hồ sơ</button></div>`;['#bible','#style'].forEach(s=>bind(s,'input',()=>state.dirty=true));bind('#save-bible','click',e=>action(e.target,async()=>{state.project=await api('projects:save',{id:p.id,bible:$('#bible').value,style:$('#style').value});state.dirty=false;toast('Đã lưu hồ sơ.');}));return;}
 if(state.tab==='memory'){el.innerHTML=`<div class="panel"><h3>Trạng thái đã xác nhận</h3><p>Tìm lại ký ức cũ theo từ khóa liên quan; kết hợp với 3 chương gần nhất và trạng thái hiện tại. Bạn vẫn nên duyệt các chi tiết quan trọng.</p>${Object.entries(p.ledger||{}).map(([k,v])=>`<div class="memory-card"><b>${esc(k)}</b><p>${esc(v)}</p></div>`).join('')||'<p>Chưa có dữ kiện được duyệt.</p>'}<h3>Các tuyến chưa giải quyết</h3><div class="read-text">${esc((p.openThreads||[]).join('\n'))||'Chưa có tuyến đang mở.'}</div></div><div class="panel"><h3>Ký ức theo chương</h3>${p.memories.map(m=>`<div class="memory-card"><b>Chương ${m.chapter}</b><p>${esc(m.summary)}</p><p>${esc((m.facts||[]).join('\n'))}</p></div>`).join('')||'<p>AI sẽ lưu ký ức sau khi kiểm tra chương.</p>'}<p>${number(p.usage.calls)} lượt gọi AI · ${number(p.usage.input)} token đầu vào · ${number(p.usage.output)} token đầu ra</p></div>`;return;}
 const c=state.chapter;
 el.innerHTML=`<div class="workspace"><div class="chapter-list">${p.chapters.map(x=>`<button class="chapter-item ${c?.number===x.number?'active':''}" data-chapter="${x.number}"><b>${x.number}. ${esc(x.title)}</b><small>${statusNames[x.status]||esc(x.status)} · ${number(x.wordCount)} từ</small></button>`).join('')||'<div class="hint">Chương sẽ xuất hiện khi bạn bắt đầu viết.</div>'}</div><div class="editor-panel">${c?`<div class="editor-heading"><h3>Chương ${c.number}</h3><span class="mini-stat" id="word-count">${number(c.wordCount)} từ</span></div><label>Dàn ý chương<textarea id="chapter-plan" rows="3">${esc(c.plan)}</textarea></label>${c.issues?.length?`<div class="notice">${c.issues.map(esc).join('<br>')}</div>`:''}<textarea id="editor" class="editor" aria-label="Nội dung chương" ${state.busy?'readonly':''}>${esc(c.content)}</textarea><div class="section-row"><span class="hint">Sửa nội dung sẽ yêu cầu kiểm tra lại chương này và các chương sau.</span><button id="save-chapter" class="primary" ${state.busy?'disabled':''}>Lưu bản thảo</button></div>`:`<div class="empty"><h3>Câu chuyện sắp bắt đầu.</h3><p>Chọn số chương trong đợt rồi bấm Viết đợt đầu.</p></div>`}</div></div>`;
 $$('.chapter-item').forEach(button=>button.onclick=async()=>{if(await leave()){state.chapter=p.chapters.find(x=>x.number===Number(button.dataset.chapter));tabContent();}});
 bind('#editor','input',e=>{state.dirty=true;$('#word-count').textContent=number(e.target.value.trim()?e.target.value.trim().split(/\s+/).length:0)+' từ';});bind('#chapter-plan','input',()=>state.dirty=true);
 bind('#save-chapter','click',e=>action(e.target,async()=>{state.project=await api('chapters:save',{id:p.id,number:c.number,content:$('#editor').value,plan:$('#chapter-plan').value});state.chapter=state.project.chapters.find(x=>x.number===c.number);state.dirty=false;tabContent();toast('Đã lưu bản thảo.');}));
}
function settingsPage(){
 $('#crumb').textContent='Kết nối AI';const s=state.settings;
 $('#content').innerHTML=`<div class="page-heading"><div><div class="eyebrow">NGƯỜI BẠN ĐỒNG SÁNG TÁC</div><h1>Kết nối AI của bạn.</h1><p>Chọn nguồn AI và model trước khi bắt đầu viết truyện.</p></div></div><div class="panel"><label>Nguồn AI<select id="provider"><option value="chatgpt">ChatGPT — dùng gói tài khoản qua đăng nhập chính thức</option><option value="gemini">Gemini — dùng API key</option><option value="openai">OpenAI — dùng API key</option></select></label><div id="provider-details"></div><div class="two"><label>Model<select id="model"><option value="${esc(s.model)}">${esc(s.model)||'Bấm Lấy danh sách model'}</option></select></label><div class="actions"><button id="load-models" class="secondary">Lấy danh sách model</button></div></div><div class="actions"><button id="save-settings" class="primary">Lưu kết nối</button><button id="test-ai" class="secondary">Thử kết nối</button></div><div class="notice">ChatGPT dùng hạn mức gói được cấp cho ứng dụng. Gemini miễn phí có giới hạn theo model. API trả phí tính theo sử dụng; app không tự chuyển sang nguồn khác.</div></div>`;
 $('#provider').value=s.provider;providerDetails();bind('#provider','change',()=>{state.dirty=true;$('#model').innerHTML='<option value="">Chọn model sau khi lưu nguồn AI</option>';providerDetails();});
 bind('#load-models','click',e=>action(e.target,async()=>{await saveSettings();const list=await api('ai:models');if(!list.length)throw new Error('Không có model khả dụng cho tài khoản.');$('#model').innerHTML=list.map(m=>`<option value="${esc(m.id)}">${esc(m.name)}</option>`).join('');if(list.some(m=>m.id===state.settings.model))$('#model').value=state.settings.model;state.dirty=true;toast('Đã lấy model. Chọn model rồi bấm Lưu kết nối.');}));
 bind('#model','change',()=>state.dirty=true);bind('#save-settings','click',e=>action(e.target,async()=>{await saveSettings();toast('Đã lưu kết nối.');}));bind('#test-ai','click',e=>action(e.target,async()=>{await saveSettings();const result=await api('ai:test');toast(result.text+' · '+number(result.usage.output)+' token đầu ra');}));
}
function providerDetails(){
 const s=state.settings,p=$('#provider').value;
 $('#provider-details').innerHTML=p==='chatgpt'?`<div class="connection-card"><h3>Tiếp tục với ChatGPT</h3><p>${s.chatgpt?.connected?'Đã kết nối '+esc(s.chatgpt.email):'Mở trình duyệt để đăng nhập và cấp quyền cho Việt Truyện. Bạn không nhập mật khẩu vào app.'}</p><div class="actions"><button id="login" class="primary">${s.chatgpt?.connected?'Đăng nhập lại':'Continue with ChatGPT'}</button><button id="cancel-login" class="quiet">Hủy đăng nhập</button>${s.chatgpt?.connected?'<button id="logout" class="secondary">Đăng xuất</button>':''}</div><p class="hint">Nếu tài khoản chưa hỗ trợ quyền dùng gói, app sẽ thông báo. Không cam kết hạn mức đủ để chạy 1.000 chương liên tục.</p></div>`:`<label>${p==='gemini'?'Gemini':'OpenAI'} API key<input id="api-key" type="password" autocomplete="off" placeholder="${(p==='gemini'?s.hasGeminiKey:s.hasOpenaiKey)?'Đã lưu key — để trống để giữ nguyên':'Nhập API key của bạn'}"></label><p class="hint">Key được mã hóa bằng kho của hệ điều hành và không đưa vào sao lưu truyện.</p>`;
 bind('#api-key','input',()=>state.dirty=true);bind('#login','click',e=>action(e.target,async()=>{state.settings.chatgpt=await api('auth:login');providerDetails();connection();toast('Đã đăng nhập. Bấm Lấy danh sách model.');}));bind('#cancel-login','click',()=>api('auth:cancel'));bind('#logout','click',e=>action(e.target,async()=>{state.settings.chatgpt=await api('auth:logout');providerDetails();connection();}));
}
async function saveSettings(){const value={provider:$('#provider').value,model:$('#model').value};if($('#api-key')?.value){value[value.provider==='gemini'?'geminiKey':'openaiKey']=$('#api-key').value;}state.settings=await api('settings:save',value);state.dirty=false;connection();}
function updatePage(){
 $('#crumb').textContent='Cập nhật ứng dụng';const u=state.update;
 $('#content').innerHTML=`<div class="page-heading"><div><div class="eyebrow">NGÀY CÀNG TỐT HƠN</div><h1>Luôn có một trang mới.</h1><p>Cập nhật Việt Truyện ngay trong ứng dụng.</p></div></div><div class="panel"><div class="section-row"><div><h3>Việt Truyện ${esc(state.version)}</h3><p>Bản cài Windows · dữ liệu truyện lưu riêng trên máy</p></div><span class="status-pill">${u.version?'Bản mới '+esc(u.version):'Phiên bản hiện tại'}</span></div><div class="notice">${esc(u.message||'Sẵn sàng kiểm tra phiên bản mới.')}</div><div class="actions"><button id="auto-update" class="primary" ${['checking','downloading'].includes(u.status)?'disabled':''}>Cập nhật ngay</button><button id="check-update" class="secondary" ${['checking','downloading'].includes(u.status)?'disabled':''}>Kiểm tra cập nhật</button>${u.status==='available'?'<button id="download-update" class="secondary">Tải bản mới</button>':''}${u.status==='ready'?'<button id="install-update" class="primary">Cài và khởi động lại</button>':''}</div></div><div class="panel"><h3>Mỗi lần cải tiến, một bản phát hành.</h3><p>App tải bản Windows mới nhất từ GitHub Releases của techzoneadapter-droid/viettruyen. Quy trình trên GitHub tạo file cài và thông tin cập nhật khi mã nguồn được đẩy lên main.</p><p>Truyện và thông tin kết nối nằm ngoài thư mục cài đặt. App sao lưu truyện trước khi cài bản cập nhật.</p></div>`;
 bind('#auto-update','click',e=>action(e.target,async()=>{state.update=await api('update:auto');updatePage();}));
 bind('#check-update','click',e=>action(e.target,async()=>{state.update=await api('update:check');updatePage();}));bind('#download-update','click',e=>action(e.target,async()=>{state.update=await api('update:download');updatePage();}));bind('#install-update','click',e=>action(e.target,()=>api('update:install')));
}
function render(){connection();$$('[data-page]').forEach(el=>el.classList.toggle('active',el.dataset.page===(state.page==='project'?'library':state.page)));if(state.page==='library')library();else if(state.page==='project')workspace();else if(state.page==='settings')settingsPage();else updatePage();$('#job-strip').classList.toggle('hidden',!state.busy);}
async function navigate(page){if(!await leave())return;state.page=page;if(page==='library')state.projects=await api('projects:list');render();}
$$('[data-page]').forEach(el=>el.onclick=()=>action(el,()=>navigate(el.dataset.page)));$('#quick-settings').onclick=()=>navigate('settings');$('#open-data').onclick=()=>action(null,()=>api('data:open'));$('#close-dialog').onclick=()=>$('#new-dialog').close();$('#pause-job').onclick=()=>api('jobs:pause');$('#abort-job').onclick=()=>api('jobs:abort');
$('#new-form').onsubmit=e=>{e.preventDefault();action($('#new-form button[type=submit]'),async()=>{const data=Object.fromEntries(new FormData(e.target));data.target=Number(data.target);data.words=Number(data.words);const p=await api('projects:create',data);$('#new-dialog').close();e.target.reset();state.projects=await api('projects:list');state.chapter=null;state.tab='chapters';await openProject(p.id);});};
window.viet.onEvent(async event=>{
 if(event.type==='update'){state.update=event;if(state.page==='update')updatePage();return;}
 if(event.type==='phase'){state.busy=true;$('#job-strip').classList.remove('hidden');$('#job-message').textContent=event.message;$('#job-detail').textContent='Mỗi bước hoàn tất đều được lưu trên máy.';return;}
 if(event.type==='status'){$('#job-message').textContent=event.message;return;}
 if(event.type==='delta'){$('#job-detail').textContent='AI đang tạo nội dung…';return;}
 if(event.type==='saved'||event.type==='finished'){
  if(event.type==='finished'){state.busy=false;$('#job-strip').classList.add('hidden');toast(event.message);}
  state.projects=await api('projects:list');if(state.page==='project'&&state.project?.id===event.project&&!state.dirty){state.project=await api('projects:get',event.project);state.chapter=state.project.chapters.find(c=>c.number===(event.chapter||state.chapter?.number))||state.project.chapters[0];workspace();}else if(state.page==='library')library();
 }
});
(async()=>{try{const data=await api('init');Object.assign(state,data);$('#version').textContent='v'+data.version;render();}catch(e){toast(e.message);}})();
