'use strict';
function queuePage(){
 $('#crumb').textContent='Hàng đợi viết truyện';
 $('#content').innerHTML=`<div class="page-heading"><div><h1>Viết nhiều thế giới cùng lúc.</h1><p>Mỗi truyện viết tuần tự từng chương; các truyện có thể chạy song song, lưu và tiếp tục riêng.</p></div></div><div class="panel"><div class="two"><label>Số truyện chạy đồng thời<select id="queue-limit">${[1,2,3,4].map(n=>`<option value="${n}">${n} truyện</option>`).join('')}</select></label><label>Số chương viết thêm mỗi truyện<input id="queue-count" type="number" value="500" min="1" max="1000"></label></div><div id="queue-select" class="queue-select">${state.projects.map(p=>`<label class="check-label"><input type="checkbox" value="${esc(p.id)}">${esc(p.title)} · <span data-project-progress="${esc(p.id)}">${p.completed}/${p.target} chương · ${progressPercent(p.completed,p.target)}%</span></label>`).join('')||'<p>Tạo dự án truyện trong thư viện trước.</p>'}</div><div class="actions"><button id="queue-add" class="primary">Chạy các truyện đã chọn</button><button id="queue-pause-all" class="secondary">Tạm dừng tất cả</button><button id="queue-stop-all" class="quiet">Dừng ngay tất cả</button></div><p class="hint">Chạy song song dùng chung hạn mức AI hiện tại. Giảm số truyện nếu gặp giới hạn tốc độ. Hết quota sẽ tạm dừng hàng đợi; không tự đổi nguồn AI. Sau khi mở lại app, bạn chủ động tiếp tục đợt đã lưu.</p></div><h2>Các đợt đang theo dõi</h2><div id="queue-rows"></div>`;
 $('#queue-limit').value=state.queue?.limit||2;
 bind('#queue-limit','change',e=>action(null,async()=>{state.queue=await api('jobs:limit',Number(e.target.value));queueRows();}));
 bind('#queue-add','click',e=>action(e.target,async()=>{const ids=$$('#queue-select input:checked').map(x=>x.value);if(!ids.length)throw new Error('Chọn ít nhất một truyện.');const count=Number($('#queue-count').value);if(!Number.isInteger(count)||count<1||count>1000)throw new Error('Nhập 1–1.000 chương.');for(const id of ids)if(!storyLocked(id))state.queue=await api('jobs:start',{id,count});queueRows();toast('Đã đưa các truyện vào hàng đợi.');}));
 bind('#queue-pause-all','click',()=>api('jobs:pause'));bind('#queue-stop-all','click',()=>api('jobs:abort'));queueRows();
}
function queueRows(){
 if(!$('#queue-rows'))return;for(const p of state.projects){const item=state.queue?.items.find(x=>x.id===p.id),el=$(`[data-project-progress="${p.id}"]`),done=item?.totalCompleted??p.completed;if(el)el.textContent=`${done}/${p.target} chương · ${progressPercent(done,p.target)}%`;}
 const names={running:'Đang chạy',queued:'Chờ lượt',paused:'Đã tạm dừng'};
 $('#queue-rows').innerHTML=(state.queue?.items||[]).map(item=>`<div class="panel" data-queue-id="${esc(item.id)}"><div class="section-row"><h3>${esc(item.title)}</h3><span class="status-pill">${names[item.status]||esc(item.status)}</span></div><p>${esc(errorText(item.message))}</p>${storyProgress(item)}<div class="actions"><button data-queue-open="${esc(item.id)}" class="secondary">Mở truyện</button>${item.status==='paused'?`<button data-queue-resume="${esc(item.id)}" class="primary">Tiếp tục đợt đã lưu</button><button data-queue-remove="${esc(item.id)}" class="quiet">Bỏ khỏi hàng đợi</button>`:`<button data-queue-pause="${esc(item.id)}" class="secondary">Tạm dừng</button><button data-queue-abort="${esc(item.id)}" class="quiet">Dừng ngay</button>`}</div></div>`).join('')||'<div class="empty"><p>Chưa có đợt chờ hoặc đang chạy. Chọn truyện phía trên để bắt đầu.</p></div>';
 for(const [attr,name] of [['pause','jobs:pause'],['abort','jobs:abort'],['resume','jobs:resume'],['remove','jobs:remove']])for(const button of $$(`[data-queue-${attr}]`))button.onclick=()=>action(button,async()=>{await api(name,button.getAttribute('data-queue-'+attr));state.queue=await api('jobs:list');queueRows();});
 for(const button of $$('[data-queue-open]'))button.onclick=()=>openProject(button.dataset.queueOpen);
}

function progressPercent(done,total){return total>0?Number((Math.min(100,Math.max(0,done/total*100))).toFixed(1)):0;}
function storyProgress(value){
 const done=value.totalCompleted??value.chapters?.filter(c=>c.status==='approved').length??0,target=value.target||1,job=value.job||value,percent=progressPercent(done,target);
 return `<div class="story-progress"><div class="progress"><strong>Toàn truyện: ${done}/${target} chương đã hoàn thành</strong><strong>${percent}%</strong></div><progress class="chapter-progress" value="${done}" max="${target}" aria-label="Tiến độ toàn truyện">${percent}%</progress>${job.currentChapter?`<p>${job.status==='running'?'Đang xử lý':'Chương xử lý gần nhất'}: <b>chương ${job.currentChapter}</b></p>`:''}${!job.planOnly&&job.requested?`<p>Đợt này: <b>${job.completed||0}/${job.requested} chương · ${progressPercent(job.completed||0,job.requested)}%</b> · còn ${job.remaining??Math.max(0,job.requested-(job.completed||0))} chương</p>`:''}<small>Chương chỉ tính hoàn thành sau khi viết và kiểm tra đạt.</small></div>`;
}
function updateStoryProgress(){const el=$('#story-progress');if(!el||!state.project)return;const item=state.queue?.items.find(x=>x.id===state.project.id);el.innerHTML=storyProgress(item||state.project);}
