const {errorText}=require('./core/messages.js');
const {JobQueue}=require('./core/queue.cjs');
const {app,BrowserWindow,ipcMain,shell,dialog,safeStorage}=require('electron');
const path=require('node:path');const fs=require('node:fs');const {pathToFileURL}=require('node:url');const {z}=require('zod');
const {Store,atomic,read}=require('./core/store.cjs');const {AI}=require('./core/ai.cjs');const {Engine}=require('./core/engine.cjs');const {ChatGPTAuth}=require('./core/auth.cjs');
const {moveStorage}=require('./core/storage.cjs');const {signals,generateIdeas}=require('./core/ideas.cjs');
const {Translator,createTranslation,options:translationOptions,terms:translationTerms}=require('./core/translation.cjs');
const {coverOptions,generateCover,autoCover,saveCover,coverPreview,coverPath}=require('./core/cover.cjs');const {storyText,storyZip,writeExport}=require('./core/export.cjs');
const autoCoverControllers=new Map();
let configFile,ideasBusy=false,translationStore,translator,queue,coverTask=null;
function repository(kind){return kind==='translation'?translationStore:store;}
const coverIdentity=z.object({id:z.string(),kind:z.enum(['story','translation']).default('story')});
async function createCoverFor(repo,p,signal){return generateCover(repo,p,imageSettings(),auth,signal);}
async function ensureExportCover(repo,p){if(p.cover){coverPath(repo,p);return p;}idle();if(!coverOptions.parse(p.coverConfig||{}).auto)throw new Error('Tạo hoặc nhập ảnh bìa trước khi xuất ZIP.');coverTask=new AbortController();emit({type:'cover:phase',project:p.id,message:'Đang tạo ảnh bìa để xuất ZIP…'});try{return await createCoverFor(repo,p,coverTask.signal);}finally{coverTask=null;emit({type:'cover:finished',project:p.id});}}
const settingsSchema=z.object({provider:z.enum(['chatgpt','gemini','openai']),model:z.string().max(200),geminiKey:z.string().max(500).optional(),openaiKey:z.string().max(500).optional()});
app.setName('VietTruyen');if(process.env.VIETTRUYEN_TEST_USER_DATA)app.setPath('userData',process.env.VIETTRUYEN_TEST_USER_DATA);let win,store,engine,auth,vault,updater;let update={status:'idle',message:'Bấm Kiểm tra cập nhật để tìm phiên bản mới.'};
function emit(event){if(win&&!win.isDestroyed())win.webContents.send('event',event);}
class Vault{
 constructor(file){this.file=file;this.value={};if(fs.existsSync(file)){if(!safeStorage.isEncryptionAvailable())throw new Error('Không mở được kho thông tin kết nối được mã hóa.');this.value=JSON.parse(safeStorage.decryptString(Buffer.from(read(file,'').data,'base64')));}}
 get(key){return this.value[key];}
 set(key,value){if(!safeStorage.isEncryptionAvailable()||(process.platform==='linux'&&safeStorage.getSelectedStorageBackend()==='basic_text'))throw new Error('Hệ điều hành chưa có kho mã hóa an toàn. Không lưu thông tin đăng nhập.');const next={...this.value,[key]:value};atomic(this.file,{data:safeStorage.encryptString(JSON.stringify(next)).toString('base64')});this.value=next;}
}
function settings(){return {...{provider:'chatgpt',model:''},...(vault.get('settings')||{})};}
function publicSettings(){const s=settings();return {provider:s.provider,model:s.model,hasGeminiKey:!!s.geminiKey,hasOpenaiKey:!!s.openaiKey,chatgpt:auth.status()};}
function imageSettings(){return {provider:'openai',model:'',...(vault.get('imageSettings')||{})};}
function publicImageSettings(){const s=imageSettings();return {provider:s.provider,model:s.model,hasGeminiKey:!!s.geminiKey,hasOpenaiKey:!!s.openaiKey};}
function idle(){if(queue?.busy()||translator?.busy()||ideasBusy||coverTask)throw new Error('Hãy tạm dừng và chờ tác vụ kết thúc trước khi thay đổi dữ liệu hoặc cập nhật.');}
function installUpdates(){
 const {autoUpdater}=require('electron-updater');updater=autoUpdater;updater.autoDownload=false;updater.autoInstallOnAppQuit=false;updater.allowDowngrade=false;
 function state(status,message,extra={}){update={status,message,...extra};emit({type:'update',...update});}
 updater.on('checking-for-update',()=>state('checking','Đang kiểm tra phiên bản mới…'));
 updater.on('update-available',info=>state('available',`Có phiên bản ${info.version}. Bấm Tải bản mới.`,{version:info.version}));
 updater.on('update-not-available',()=>state('current','Bạn đang dùng phiên bản mới nhất.'));
 updater.on('download-progress',p=>state('downloading',`Đang tải: ${Math.round(p.percent)}%`,{percent:p.percent}));
 updater.on('update-downloaded',info=>state('ready',`Đã tải phiên bản ${info.version}. Bấm Cài và khởi động lại.`,{version:info.version}));
 updater.on('error',()=>state('error','Không kiểm tra hoặc tải được bản phát hành. Kiểm tra mạng rồi thử lại.'));
}
function handle(name,fn){ipcMain.handle(name,async(event,...args)=>{const expected=pathToFileURL(path.join(__dirname,'ui/index.html')).href;if(event.sender!==win.webContents||event.senderFrame?.url!==expected)throw new Error('Nguồn yêu cầu không hợp lệ.');try{return {ok:true,data:await fn(...args)};}catch(e){return {ok:false,error:errorText(e)};}});}
app.whenReady().then(()=>{
 configFile=path.join(app.getPath('userData'),'storage.json');const config=read(configFile,{});const root=config.root||path.join(app.getPath('userData'),'data');if(config.root&&!fs.existsSync(root))throw new Error('Không tìm thấy thư mục truyện '+root+'. Kết nối lại ổ đĩa rồi mở app.');store=new Store(root);vault=new Vault(path.join(app.getPath('userData'),'credentials.json'));auth=new ChatGPTAuth(vault,url=>shell.openExternal(url));engine=new Engine(store,new AI(settings,auth),emit);translationStore=new Store(path.join(store.root,'translations'));translator=new Translator(translationStore,engine.ai,emit);for(const item of translationStore.list()){const p=translationStore.load(item.id);if(p.job?.status==='running'){p.job={status:'paused',message:'App đã đóng giữa tác vụ. Bấm Tiếp tục dịch.'};translationStore.save(p);}}
 const afterPlan=async(p,signal)=>{const controller=new AbortController();autoCoverControllers.set(p.id,controller);try{await autoCover(store,p,imageSettings(),auth,AbortSignal.any([signal,controller.signal]),emit);}catch(e){if(signal.aborted)throw e;p.coverError='Đã hủy tạo bìa. Có thể tạo lại trong tab Bìa truyện.';store.save(p);}finally{autoCoverControllers.delete(p.id);}};
 engine.afterPlan=afterPlan;
 queue=new JobQueue(store,event=>{const worker=new Engine(store,engine.ai,event);worker.afterPlan=afterPlan;return worker;},emit);

 for(const p of store.list()){const v=store.load(p.id);if(v.job?.status==='running'){v.job={...v.job,status:'paused',message:'Ứng dụng đã đóng giữa tác vụ. Bấm Tiếp tục để chạy từ phần đã lưu.'};store.save(v);}}
 installUpdates();
 handle('init',()=>({projects:store.list(),translations:translationStore.list(),queue:queue.snapshot(),settings:publicSettings(),imageSettings:publicImageSettings(),version:app.getVersion(),update,storage:{root:store.root},ideas:read(path.join(store.root,'ideas.json'),null)}));
 handle('projects:list',()=>store.list());handle('projects:get',id=>store.load(z.string().parse(id)));
 handle('projects:create',input=>store.create(input));
 handle('projects:save',input=>{
  const v=z.object({id:z.string(),bible:z.string().max(30000),style:z.string().max(4000)}).parse(input);if(queue.locked(v.id))throw new Error('Tạm dừng truyện này trước khi sửa hồ sơ.');const p=store.load(v.id);store.backup(p);p.bible=v.bible;p.style=v.style;return store.save(p);
 });
 handle('chapters:save',input=>{
  const v=z.object({id:z.string(),number:z.number().int().min(1).max(1000),content:z.string().max(200000),plan:z.string().max(6000)}).parse(input);if(queue.locked(v.id))throw new Error('Tạm dừng truyện này trước khi sửa chương.');const p=store.load(v.id),c=p.chapters.find(c=>c.number===v.number);if(!c)throw new Error('Không tìm thấy chương.');store.backup(p);
  if(c.content!==v.content){c.content=v.content;c.wordCount=v.content.trim()?v.content.trim().split(/\s+/).length:0;p.memories=p.memories.filter(m=>m.chapter<v.number);p.ledger=Object.assign({},...p.memories.map(m=>m.stateUpdates||{}));p.openThreads=p.memories.at(-1)?.openThreads||[];for(const later of p.chapters.filter(x=>x.number>=v.number&&x.content)){later.status='needs_review';later.issues=['Nội dung chương trước đã thay đổi; cần kiểm tra lại.'];}}
  c.plan=v.plan;return store.save(p);
 });
 handle('jobs:list',()=>queue.snapshot());
 handle('jobs:limit',value=>queue.setLimit(z.number().int().min(1).max(4).parse(value)));
 handle('jobs:resume',id=>{if(translator.busy()||ideasBusy||coverTask)throw new Error('Chờ tác vụ dịch hoặc ảnh hoàn tất.');return queue.resume(z.string().parse(id));});
 handle('jobs:remove',id=>queue.remove(z.string().parse(id)));
 handle('jobs:start',input=>{const v=z.object({id:z.string(),count:z.number().int().min(1).max(1000),planOnly:z.boolean().default(false)}).parse(input);if(translator.busy()||ideasBusy||coverTask)throw new Error('Chờ tác vụ dịch hoặc ảnh hoàn tất.');return queue.enqueue(v.id,v.count,{planOnly:v.planOnly});});
 handle('jobs:pause',id=>{if(translator.busy()&&!id)translator.pause();else queue.pause(id?z.string().parse(id):undefined);return true;});
 handle('jobs:abort',id=>{if(translator.busy()&&!id)translator.abort();else queue.pause(id?z.string().parse(id):undefined,true);return true;});
 handle('settings:save',input=>{idle();const v=settingsSchema.parse(input);const s=settings();vault.set('settings',{...s,...v,geminiKey:v.geminiKey===undefined?s.geminiKey:v.geminiKey,openaiKey:v.openaiKey===undefined?s.openaiKey:v.openaiKey});return publicSettings();});
 handle('images:settings',()=>publicImageSettings());
 handle('images:save',input=>{idle();const v=settingsSchema.extend({provider:z.enum(['gemini','openai'])}).parse(input),s=imageSettings();vault.set('imageSettings',{...s,...v,geminiKey:v.geminiKey===undefined?s.geminiKey:v.geminiKey,openaiKey:v.openaiKey===undefined?s.openaiKey:v.openaiKey});return publicImageSettings();});
 handle('auth:login',()=>{idle();return auth.login();});handle('auth:cancel',()=>auth.cancel());handle('auth:logout',()=>{idle();return auth.logout();});handle('ai:models',()=>{idle();return engine.ai.models();});
 handle('ai:test',async()=>{idle();const r=await engine.ai.generate('Chỉ trả lời bằng tiếng Việt.','Trả lời đúng một câu: Kết nối thành công.');return {text:r.text,usage:r.usage};});
 handle('export',async input=>{
  const v=z.object({id:z.string(),format:z.enum(['txt','json','zip'])}).parse(input);let p=store.load(v.id);const r=await dialog.showSaveDialog(win,{defaultPath:p.title.replace(/[<>:"/\\|?*]/g,'_')+'.'+v.format,filters:[{name:v.format==='zip'?'Truyện kèm ảnh bìa':v.format==='txt'?'Văn bản':'Sao lưu truyện',extensions:[v.format]}]});if(r.canceled)return null;
  if(v.format==='zip'){idle();p=await ensureExportCover(store,store.load(v.id));writeExport(r.filePath,storyZip(store,p));}else writeExport(r.filePath,v.format==='json'?JSON.stringify(p,null,2):storyText(p));return r.filePath;
 });
 handle('import',async()=>{idle();const r=await dialog.showOpenDialog(win,{filters:[{name:'Sao lưu Việt Truyện',extensions:['json']}],properties:['openFile']});if(r.canceled)return null;const file=r.filePaths[0];if(fs.statSync(file).size>50*1024*1024)throw new Error('Bản sao lưu lớn hơn 50 MB.');return store.import(JSON.parse(fs.readFileSync(file,'utf8')));});

 handle('translation:list',()=>translationStore.list());handle('translation:get',id=>translationStore.load(z.string().parse(id)));
 handle('translation:create',input=>{idle();const v=translationOptions.extend({text:z.string().min(1).max(20000000)}).parse(input);return createTranslation(translationStore,v,[{title:'Chương 1',text:v.text}]);});
 handle('translation:import',async input=>{idle();const v=translationOptions.extend({encoding:z.enum(['utf-8','utf-16le','gb18030']).default('utf-8')}).parse(input);const result=await dialog.showOpenDialog(win,{title:'Nhập truyện để dịch',filters:[{name:'Truyện dạng văn bản',extensions:['txt']}],properties:['openFile','multiSelections']});if(result.canceled)return null;idle();const files=result.filePaths.slice().sort((a,b)=>a.localeCompare(b,'vi',{numeric:true}));if(files.length>1000)throw new Error('Tối đa 1.000 file.');let total=0;const sources=files.map(file=>{const size=fs.statSync(file).size;total+=size;if(size>30*1024*1024||total>60*1024*1024)throw new Error('File quá lớn. Chia thành từng quyển để nhập.');let text;try{text=new TextDecoder(v.encoding,{fatal:true}).decode(fs.readFileSync(file));}catch{throw new Error('Không đọc được chữ. Chọn lại mã hóa UTF-8, UTF-16 hoặc GB18030.');}return {title:path.basename(file,'.txt'),text};});return createTranslation(translationStore,v,sources);});
 handle('translation:settings',input=>{idle();const v=z.object({id:z.string(),style:z.string().trim().min(1).max(4000),glossary:z.string().max(20000)}).parse(input);const glossary=translationTerms(v.glossary),p=translationStore.load(v.id);translationStore.backup(p);p.style=v.style;p.translation.glossary=glossary;return translationStore.save(p);});
 handle('translation:save',input=>{idle();const v=z.object({id:z.string(),number:z.number().int().min(1).max(1000),content:z.string().trim().min(1).max(1000000)}).parse(input);const p=translationStore.load(v.id),c=p.chapters.find(x=>x.number===v.number);if(!c)throw new Error('Không tìm thấy chương.');translationStore.backup(p);c.content=v.content;c.status='approved';c.manual=true;c.issues=[];c.wordCount=v.content.split(/\s+/).length;c.segments.forEach(s=>s.reviewed=true);return translationStore.save(p);});
 handle('translation:start',input=>{idle();const v=z.object({id:z.string(),count:z.number().int().min(1).max(1000)}).parse(input);void translator.run(v.id,v.count).catch(e=>emit({type:'translation:finished',message:errorText(e)}));return true;});
 handle('translation:export',async input=>{const v=z.object({id:z.string(),format:z.enum(['txt','json','zip'])}).parse(input);let p=translationStore.load(v.id);const result=await dialog.showSaveDialog(win,{defaultPath:p.title.replace(/[<>:"/\\|?*]/g,'_')+'-ban-dich.'+v.format,filters:[{name:v.format==='zip'?'Bản dịch kèm bìa':v.format==='txt'?'Bản dịch':'Sao lưu gốc và bản dịch',extensions:[v.format]}]});if(result.canceled)return null;if(v.format==='zip'){idle();p=await ensureExportCover(translationStore,translationStore.load(v.id));writeExport(result.filePath,storyZip(translationStore,p));}else writeExport(result.filePath,v.format==='json'?JSON.stringify(p,null,2):storyText(p));return result.filePath;});
 handle('cover:preview',async input=>{const v=coverIdentity.parse(input),repo=repository(v.kind);return coverPreview(repo,repo.load(v.id));});
 handle('cover:settings',input=>{idle();const v=coverIdentity.extend({config:coverOptions,apiKey:z.string().max(500).optional()}).parse(input),repo=repository(v.kind),p=repo.load(v.id);if(v.apiKey){const source=v.config.provider==='current'?imageSettings().provider:v.config.provider;if(source==='chatgpt')throw new Error('ChatGPT dùng đăng nhập, không nhập key.');vault.set('imageSettings',{...imageSettings(),[source==='gemini'?'geminiKey':'openaiKey']:v.apiKey});}repo.backup(p);p.coverConfig=v.config;repo.save(p);return {project:p,settings:publicSettings(),imageSettings:publicImageSettings()};});
 handle('cover:generate',async input=>{idle();const v=coverIdentity.parse(input),repo=repository(v.kind),p=repo.load(v.id);coverTask=new AbortController();emit({type:'cover:phase',project:p.id,message:'Đang tạo ảnh bìa…'});try{const result=await createCoverFor(repo,p,coverTask.signal);return result;}catch(e){p.coverError=errorText(e);repo.save(p);throw e;}finally{coverTask=null;emit({type:'cover:finished',project:p.id});}});
 handle('cover:cancel',input=>{coverTask?.abort();if(input?.id)autoCoverControllers.get(z.string().parse(input.id))?.abort();return true;});
 handle('cover:import',async input=>{idle();const v=coverIdentity.parse(input),repo=repository(v.kind),result=await dialog.showOpenDialog(win,{title:'Chọn ảnh bìa tối thiểu 800 × 1200 px',filters:[{name:'Ảnh bìa',extensions:['jpg','jpeg','png','webp']}],properties:['openFile']});if(result.canceled)return null;idle();const file=result.filePaths[0];if(fs.statSync(file).size>5*1024*1024)throw new Error('Ảnh tải lên tối đa 5 MB.');const p=repo.load(v.id);coverTask=new AbortController();try{return await saveCover(repo,p,fs.readFileSync(file),coverOptions.parse(p.coverConfig||{}),{provider:'uploaded',model:''});}finally{coverTask=null;}});
 handle('cover:export',async input=>{const v=coverIdentity.parse(input),repo=repository(v.kind),p=repo.load(v.id);const source=coverPath(repo,p),result=await dialog.showSaveDialog(win,{defaultPath:'bia.'+p.cover.format,filters:[{name:'Ảnh bìa',extensions:[p.cover.format]}]});if(result.canceled)return null;writeExport(result.filePath,fs.readFileSync(source));return result.filePath;});
 handle('data:open',()=>shell.openPath(store.root));
 handle('data:location',()=>({root:store.root}));
 handle('data:change',async()=>{idle();const selection=await dialog.showOpenDialog(win,{title:'Chọn thư mục trống để lưu truyện',properties:['openDirectory','createDirectory']});if(selection.canceled)return null;idle();const next=moveStorage(store.root,selection.filePaths[0],target=>atomic(configFile,{root:target}));store=next;engine.store=next;queue.store=next;queue.save();translationStore=new Store(path.join(next.root,'translations'));translator.store=translationStore;return {root:next.root,projects:next.list()};});
 handle('ideas:fetch',async input=>{idle();ideasBusy=true;try{const snapshot=await signals(z.string().parse(input));atomic(path.join(store.root,'ideas.json'),snapshot);return snapshot;}finally{ideasBusy=false;}});
 handle('ideas:generate',async input=>{idle();const genre=z.string().trim().min(1).max(160).parse(input);const snapshot=read(path.join(store.root,'ideas.json'),null);if(!snapshot?.items?.length)throw new Error('Lấy tín hiệu web trước khi tạo ý tưởng.');ideasBusy=true;try{const result=await generateIdeas(engine.ai,snapshot,genre);atomic(path.join(store.root,'ideas.json'),result);return result;}finally{ideasBusy=false;}});
 handle('ideas:source',async input=>{const snapshot=read(path.join(store.root,'ideas.json'),null);const index=z.number().int().min(0).max(19).parse(input);const item=snapshot?.items?.[index];if(!item)throw new Error('Không tìm thấy nguồn.');const url=new URL(item.url);if(url.protocol!=='https:'||url.hostname!=='news.google.com')throw new Error('Nguồn không hợp lệ.');await shell.openExternal(url.href);return true;});
 handle('update:auto',async()=>{idle();if(!app.isPackaged){update={status:'dev',message:'Cập nhật chỉ hoạt động trong bản đã cài đặt.'};return update;}if(['checking','downloading'].includes(update.status))return update;if(update.status!=='ready'){await updater.checkForUpdates();if(update.status==='available')await updater.downloadUpdate();}if(update.status==='ready'){idle();for(const repo of [store,translationStore])for(const item of repo.list())repo.backup(repo.load(item.id));updater.quitAndInstall(false,true);}return update;});
 handle('update:check',async()=>{idle();if(!app.isPackaged){update={status:'dev',message:'Cập nhật chỉ hoạt động trong bản đã cài đặt.'};return update;}if(['checking','downloading'].includes(update.status))return update;await updater.checkForUpdates();return update;});
 handle('update:download',async()=>{idle();if(update.status!=='available')throw new Error('Hãy kiểm tra bản mới trước.');await updater.downloadUpdate();return update;});
 handle('update:install',()=>{idle();if(update.status!=='ready')throw new Error('Bản cập nhật chưa tải xong.');for(const repo of [store,translationStore])for(const item of repo.list())repo.backup(repo.load(item.id));updater.quitAndInstall(false,true);return true;});
 win=new BrowserWindow({width:1380,height:900,minWidth:1050,minHeight:700,title:'Việt Truyện',backgroundColor:'#f7f6f2',autoHideMenuBar:true,webPreferences:{preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true}});
 win.webContents.setWindowOpenHandler(()=>({action:'deny'}));win.webContents.on('will-navigate',e=>e.preventDefault());win.loadFile(path.join(__dirname,'ui/index.html'));
 win.on('close',e=>{if(ideasBusy){e.preventDefault();void dialog.showMessageBox(win,{message:'Đang lấy tín hiệu hoặc tạo ý tưởng. Chờ hoàn tất rồi đóng app.'});return;}if(queue.busy()||translator.busy()||coverTask){e.preventDefault();dialog.showMessageBox(win,{type:'question',buttons:['Tiếp tục viết','Dừng và đóng'],defaultId:0,cancelId:0,message:'Có tác vụ đang chạy',detail:'Dừng sẽ giữ lại các bước đã lưu. Bạn có thể tiếp tục khi mở app.'}).then(r=>{if(r.response===1){queue.shutdown();translator.abort();coverTask?.abort();const done=setInterval(()=>{if(!queue.busy()&&!translator.busy()&&!coverTask){clearInterval(done);win.close();}},200);}});}});
}).catch(error=>{dialog.showErrorBox('Không mở được Việt Truyện',error.message);app.quit();});
app.on('window-all-closed',()=>{auth?.cancel();app.quit();});
